language: none
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq

install:
    - sudo apt-get -y install gcc-6 g++-6
    - sudo apt-get -y install libusb-1.0-0-dev pkg-config qt510base qt510declarative qt510quickcontrols qt510quickcontrols2 qt510charts-no-lgpl qt510multimedia libpulse0 libfaad-dev libfftw3-dev librtlsdr-dev libusb-1.0-0-dev mesa-common-dev libglu1-mesa-dev libpulse-dev
    - source /opt/qt510/bin/qt510-env.sh
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

script:
  - DATE=`date +%Y%m%d`
  - GIT_HASH=`git rev-parse --short HEAD`
  - # https://github.com/airspy/airspyone_host#how-to-build-the-host-software-on-linux
  - wget https://github.com/airspy/host/archive/master.zip
  - unzip master.zip
  - cd airspyone_host-master/
  - mkdir build
  - cd build
  - cmake ../ -DINSTALL_UDEV_RULES=ON -DCMAKE_INSTALL_PREFIX=/usr
  - make
  - sudo make install
  - sudo ldconfig
  - cd ../..
  - mkdir build
  - cd build
  - qmake PREFIX=/usr ..
  - make -j4
  - # sudo make INSTALL_ROOT=../appdir install ; sudo chown -R $USER appdir ; find appdir/
  - # "make install" seems not implemented, hence going though the following steps manually:
  - cd ..
  - find build/
  - mkdir -p ./appdir/usr/share/applications
  - cp welle-io.desktop ./appdir/usr/share/applications
  - mkdir -p ./appdir/usr/bin
  - cp build/welle-io ./appdir/usr/bin
  - mkdir -p ./appdir/usr/lib
  - mkdir -p ./appdir/usr/share/icons/hicolor/512x512/apps/
  - cp icon.png appdir/usr/share/icons/hicolor/512x512/apps/welle-io.png

after_success:
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -qmldir=. -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -qmldir=. -appimage
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  #- curl --upload-file ./welle*.AppImage https://transfer.sh/welle_io-git."$GIT_HASH"-x86_64.AppImage
  # Rename
  - mv welle.io-x86_64.AppImage "$DATE"_"$GIT_HASH"_Linux_welle-io-x86_64.AppImage
  # Prepare bintray deploy
  - sed -e "s/\${VERSION}/"$DATE"_"$GIT_HASH"/" .travis-bintray-deploy.json.template >travis-bintray-deploy.json

deploy:
  on:
   branch: next
  provider: bintray
  file: "travis-bintray-deploy.json"
  user: "albrechtl"
  skip_cleanup: true
  key:
    secure: "FvQOjUijZP1es80QQAIuBUFSvtsrJC03STlNu+Uvl9RUlgtWuXk1c5g9zggYgbm61LL5NTb5BLQggDkvuBdiNbE9CE2Y2MPWh1sava/n1z0vVgNoYjOIX9HO4s8fQkHs70Xx5XtUb1nAx2u4CDBt0wUWfbz6r77w3PJ5d1TpZjj+u3FOGUq9EW1ECQnBXuAHtu5WKdN3hOSw7WLXx4yQwR6RHF9zXE/dzvjA4B/JHY5Jfm3le4sCjKe4V4HDlqcmzorww8b4g+RezL0h+RGyqt0zHufa11lMa3VsZcTrQAhTZha7b2Sia1Vy+jWTtqb/BJM/fz0iOmoQNlual5lNPYmb0r3fyU4HTSnlH8FK+ifQBsCE6qUSdsOpOyKq+cX+jBaZXmgDqhA9bUofsAh/jtA3WgBX2GE6sSX0Z1/3HJnUzzEjgCMjiK6XYjl5qKZ20At68m9msjNom2CQ+QAGqLCsn6ADo0prxBHqUst5IeoKu30QdoarUbZvYliE7OLqewUsuGE8Dqwq78Qw6wWTlVauUpOrvmavoobUd7h4jE7xoko3KEfLGB5jGSKcTysKR4fVPAAEQYjfsImI9083VdY2UN7MGw3dHncH2N2Ncp8bKjjSrNg2Ve8IKtHryn/QjvAwnfdyO4vUqY1+40YmmNaiDRVsYZc2FisKSPsG4ws="

after_deploy:
  script: 
    # Delete old builds on bintray
    # .bintray_delete_old_version.py albrechtl <secret>
    secure: "V3FvzWRPhTyU/WLZ+bYXhV2AfOkY3Owgv+8t6I8q11IRZFWof+rdR1fWNK2P9wGXT+mS4Jo7RhFQQ6uOu5yd3yBJ6eiQw4R4hA9kYkhb2yGmkeEF1KRrEmPwI50A7ZzPNavV8z21b6XaHzLjvaWuoOD/zYrn8nezyMCSNCPqqHYUOTFeKC+0fZc4K8p7PZg4JIEFfGGJrGZHJn7SGCAJqpvsqBwygb7vZpdaV7qwNAUV9geOkngQyEMO7ZYNwY6UzApk6GPBa4XqyVIxtgyaX3VbHYHD1TyIY8yOF57Vsn2mUi8ZtE+iQJUtPsgCPfRNuCEXCFb5iJpTwkexEl02j7FRj9cxAFGe+TrDHbLcIXQFjRbNHcff/aeZ65IwGtw7wXcJxXIFRpGtSBgSCC3Hhyy3n90ChE+p12gMlzDWEQmJe0kgE+S9xwoBKKouraVsECa2uKnEsRk9NwIWcaxTJmm7Pnoz4km8PWjFMN7doINZivcwr7EZgcrICqSdz/G7HGn5PD7B7fqfHMD3fWPssCtYZ64ySkC7qU4Vwn31DBBDtrlg/ewoWNbWVpwmRalGYCrn2AMl46GgwVs7jnL6Qz0tkXfqA+30fXWfcRYlNs+gnpKoxxIrUCgTbxPCE3KGQuGdR2XKC52zissmQUGsJlpj3aR0euWDIQXn3oN4Ijw="

