- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "Impressum"
  url: "/impressum/"
  title: "Impressum"

- name: "Datenschutzerklaerung"
  url: "/datenschutzerklaerung/"
  title: "Datenschutzerklärung"

